# Generated by Django 4.2.18 on 2025-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_path', models.URLField()),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
