# Generated by Django 4.2.18 on 2025-01-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_genre_reviewentity_season_seriesreview_seriesgenre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviereview',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='average_rating',
        ),
    ]
