# Generated by Django 4.2.18 on 2025-02-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_moviereview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieslist',
            name='average_rating',
        ),
    ]
