# Generated by Django 4.2.18 on 2025-02-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_serieslist_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesreview',
            options={'ordering': ['date_created']},
        ),
    ]
