# Generated by Django 4.2.18 on 2025-02-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_seriesreview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_count', models.IntegerField()),
                ('description', models.TextField()),
                ('first_air_date', models.DateField()),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('poster_path', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.serieslist')),
            ],
        ),
        migrations.AlterField(
            model_name='seasonreview',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seasonlist'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
