# Generated by Django 4.2.18 on 2025-02-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_seasonlist_alter_seasonreview_season_delete_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonlist',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
